version: '3'

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:









services:
  app:
    build: .
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    command: bundle exec puma -C config/puma.rb
    environment:
      - RAILS_ENV=production
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - ./containers/nginx/log:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - app
