version: '3'

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:

services:
  app:
    image: zsbing84/circleci-test
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    environment:
      - RAILS_ENV=production
    command: bundle exec puma -C config/puma.rb
  web:
    image: zsbing84/nginx-test
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - ./containers/nginx/log:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - app
